### ISSUE TITLE
babel-core

### ISSUE THREAD

**Issue by folkvir** [RAN3D/foglet-scripts#2]
babel-core should be installed with babel-loader

Leading to this error otherwise: ` Error: Module build failed: Error: Cannot find module 'babel-core'`

This happened while:
```bash
npm install --save foglet-core
npm install --save-dev foglet-scripts karma-firefox-luncher
npm test
``` 

output: 
```
ERROR in ./tests/sometests-test.js
Module build failed: Error: Cannot find module 'babel-core'
```

**Comment by Callidon** [comment]
fixed with f4433806d414ed1b0870962046a9dfd7c70ecc94
